// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8k89ywpQm4aphvLJ5wH0KuW9fhOzgYNE',
    appId: '1:80346394917:web:9057e98d6fae5da9fd2acc',
    messagingSenderId: '80346394917',
    projectId: 'bjpleader-25064',
    authDomain: 'bjpleader-25064.firebaseapp.com',
    storageBucket: 'bjpleader-25064.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHbnz6H2KHtbOx0fc7Bf_eDJYfCyVfmLo',
    appId: '1:80346394917:android:e468e2d117f26128fd2acc',
    messagingSenderId: '80346394917',
    projectId: 'bjpleader-25064',
    storageBucket: 'bjpleader-25064.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqsJWbWHNv9mUbiL9TIr5sTiyNTpdd6dg',
    appId: '1:80346394917:ios:6f719aeae9589af7fd2acc',
    messagingSenderId: '80346394917',
    projectId: 'bjpleader-25064',
    storageBucket: 'bjpleader-25064.appspot.com',
    iosBundleId: 'com.example.bjpLeader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqsJWbWHNv9mUbiL9TIr5sTiyNTpdd6dg',
    appId: '1:80346394917:ios:be2837de757a901efd2acc',
    messagingSenderId: '80346394917',
    projectId: 'bjpleader-25064',
    storageBucket: 'bjpleader-25064.appspot.com',
    iosBundleId: 'com.example.bjpLeader.RunnerTests',
  );
}
